# gui/aboutpopup.kv
# Define la apariencia de la ventana emergente "Acerca de".

#:set COLOR_PRIMARY (0/255, 105/255, 170/255, 1)
#:set COLOR_TEXT_LIGHT (1, 1, 1, 1)
#:set COLOR_TEXT_DARK (0.1, 0.1, 0.1, 1)

<AboutPopup>:
    title: 'Acerca de ScanIA'
    # Tamaño ajustado para el nuevo contenido
    size_hint: 0.8, 0.85
    auto_dismiss: False

    BoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(15)
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1 # Fondo blanco
            Rectangle:
                pos: self.pos
                size: self.size

        ScrollView:
            bar_width: dp(10)
            do_scroll_x: False
            Label:
                size_hint_y: None
                height: self.texture_size[1]
                text_size: self.width, None
                padding: dp(10), dp(10)
                markup: True
                color: COLOR_TEXT_DARK
                valign: 'top'
                halign: 'left'
                text: root.about_text

        Button:
            text: 'Cerrar'
            size_hint_y: None
            height: dp(45)
            on_press: root.dismiss()
            background_normal: ''
            background_color: COLOR_PRIMARY
            color: COLOR_TEXT_LIGHT